Fix handling of mixed paths in removeSubsumedPaths
It turns out that the os.path.commonpath function cannot handle the case
where a mixture of relative and absolute paths is provided as input and
will raise an exception:
  > ValueError: Can't mix absolute and relative paths

This change fixes the problem by making sure we provide only absolute
paths as input.